const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');

const html = fs.readFileSync('templates/app_operativa_demo.html', 'utf8');
const script = html.slice(html.lastIndexOf('<script>') + 8, html.lastIndexOf('</script>'));

new vm.Script(script);
assert.match(html, /ID interno \(inmutable\)/);
assert.match(html, /data-tech-permission="editClientData"/);
assert.match(html, /data-tech-permission="editIds"/);
assert.match(html, /data-tech-permission="switchViews"/);
assert.match(html, /function can\(permission\)/);
assert.match(html, /function openRoot\(name\)/);
assert.match(html, /function initializeBrowserNavigation\(\)/);
assert.match(html, /window\.history\.pushState/);
assert.match(html, /window\.history\.replaceState/);
assert.match(html, /url\.hash=guard\?'hsc-proteccion'/);
assert.match(html, /for\(let index=1;index<restoredStack\.length;index\+\+\)/);
assert.match(html, /addEventListener\('popstate'/);
assert.match(html, /partnerFaults:\['partner','partnerFaults'\]/);
assert.match(html, /\$\('#backBtn'\)\.hidden=false/);
assert.match(html, /data-switch-mode="tech"/);
assert.match(html, /data-switch-mode="admin"/);
assert.match(html, /HSC Partner no puede crear, modificar ni finalizar reportes/);
assert.match(html, /id="inviteTechPermissions"/);
assert.match(html, /id="inviteClientPermissions"/);
assert.match(html, /\/api\/operaciones\/clients/);
assert.match(html, /\/api\/operaciones\/equipment/);
assert.match(script, /Equipo desactivado; historial conservado/);
assert.match(html, /\/api\/operaciones\/reports\/draft/);
assert.match(html, /\/api\/operaciones\/reports\/finalize/);
assert.match(html, /\/evidence\/reset/);
assert.match(html, /evidence\/\$\{index\+1\}/);
assert.match(script, /async function clearEvidenceDraft\([^)]*\)/);
assert.match(script, /Reporte guardado · \$\{photos\.length\} foto\(s\) subiendo/);
assert.match(script, /showView\('equipment'\);[\s\S]*finishReportInBackground\(upload\)/);
assert.doesNotMatch(script, /await finishReportInBackground\(upload\)/);
assert.match(script, /await clearEvidenceDraft\(upload\.key\)/);
assert.match(html, /Sincronizar Google/);
assert.match(html, /id="reloadApp"/);
assert.match(html, /id="orderClients"/);
assert.match(html, /hsc-operaciones-navigation/);
assert.doesNotMatch(html, />Compartir PDF</);
assert.doesNotMatch(html, />Descargar PDF</);
assert.doesNotMatch(html, />Antes</);
assert.doesNotMatch(html, />Después</);
assert.match(html, /id="reportEvidencePreview"/);
assert.doesNotMatch(html, /Firma del técnico y del cliente|Agregar firma|<h2>Firmas<\/h2>/);
assert.match(html, /data-doc-field="client"/);
assert.match(html, /data-doc-field="round"/);
assert.match(html, /data-doc-field="date"/);
assert.match(html, /data-doc-field="equipment"/);
assert.match(html, /data-doc-field="pressure1"/);
assert.match(html, /data-doc-field="amperage1"/);
assert.match(html, /data-doc-field="temperature"/);
assert.doesNotMatch(html, /data-doc-field="period"/);
assert.match(html, /class="partner-dashboard"/);
assert.match(html, /<nav class="bottom-nav">[\s\S]*>Agenda<[\s\S]*>Clientes<[\s\S]*>Perfil</);
assert.match(html, /body\[data-active-mode="partner"\] \.bottom-nav\{display:none!important\}/);
assert.match(script, /document\.body\.dataset\.activeMode=currentMode/);
assert.match(html, /id="clientsModeBar" hidden/);
assert.match(html, /id="partnerClientChooser" hidden/);
assert.match(html, /id="partnerClientSelect"/);
assert.match(script, /function renderPartnerDashboard\(\)/);
assert.match(html, /data-partner-equipment/);
assert.match(script, /button\.dataset\.partnerEquipment/);
assert.match(html, /data-tech-only/);
assert.match(script, /currentMode==='partner'\?'true':'false'/);
assert.match(script, /\$\('#partnerClientSelect'\)\.onchange/);
assert.match(html, /id="partnerPdfButton"/);
assert.match(html, /id="partnerRoundAction"/);
assert.match(html, /id="partnerFaultAction"/);
assert.match(html, /id="faultEquipment"/);
assert.match(html, /id="partnerFaultPreview"/);
assert.match(html, /id="partnerFaultFull"/);
assert.match(script, /\/api\/operaciones\/faults/);
assert.match(script, /function renderPartnerFaults\(\)/);
assert.match(html, /id="faultDetailModal"/);
assert.match(html, /id="resolveFault"/);
assert.match(script, /data-fault-id/);
assert.match(script, /\/api\/operaciones\/faults\/\$\{encodeURIComponent\(selectedFault\)\}\/resolve/);
assert.match(html, /class="partner-client-data"[\s\S]*>Nombre<[\s\S]*id="partnerClientName"[\s\S]*>Dirección<[\s\S]*id="partnerClientAddress"/);
assert.doesNotMatch(html, /<b>Equipos<\/b><\/button><button class="quick-card" data-partner-action="reports"/);
assert.doesNotMatch(html, />Guardar en maqueta</);
assert.doesNotMatch(script, /location\.href\s*=|location\.assign\(/);

console.log('OK: IDs protegidos, permisos por técnico, modos y regreso interno presentes.');
