const fs=require('node:fs'),assert=require('node:assert/strict');
const html=fs.readFileSync('templates/app_operativa_demo.html','utf8');
assert.match(html,/\.photo-trigger\{[^}]*min-height:52px/);
assert.match(html,/-webkit-user-select:none/);
assert.match(html,/id="reportEvidence"[^>]*multiple/);
assert.match(html,/id="reportEvidenceSlots"/);
assert.match(html,/for="reportEvidenceCamera" data-evidence-target-slot/);
assert.match(html,/for="reportEvidenceSingle" data-evidence-target-slot/);
assert.match(html,/for="reportEvidence">▧ Elegir varias/);
assert.match(html,/bulkSelection\?\[\.\.\.vacant\]/);
console.log('OK: seis espacios directos usan selectores nativos y la carga múltiple conserva el orden.');
